### ISSUE TITLE
"Can't concat string to bytes" error

### ISSUE THREAD

**Issue by dllabs** [vtbassmatt/azf-wsgi#4]
I set up a Django project as per instructions, changing only the 'app' prefix to 'api'.

Going to the api/admin page presents the user with the login page, but as soon as they enter their credentials and hit enter they get the error 'can't concat str to bytes'.
Also at api/  (the app is a GraphQL api) there is the same error: 'can't concat str to bytes'

Here is the trace for the admin error:

    Traceback:

    File "C:\Users\bob\Documents\Projects\potato-face\env\lib\site-packages\django\core\handlers\exception.py" in inner
      34.             response = get_response(request)

    File "C:\Users\bob\Documents\Projects\potato-face\env\lib\site-packages\django\core\handlers\base.py" in _get_response
      117.             response = middleware_method(request, callback, callback_args, callback_kwargs)

    File "C:\Users\bob\Documents\Projects\potato-face\env\lib\site-packages\django\middleware\csrf.py" in process_view
      294.                     request_csrf_token = request.POST.get('csrfmiddlewaretoken', '')

    File "C:\Users\bob\Documents\Projects\potato-face\env\lib\site-packages\django\core\handlers\wsgi.py" in _get_post
      111.             self._load_post_and_files()

    File "C:\Users\bob\Documents\Projects\potato-face\env\lib\site-packages\django\http\request.py" in _load_post_and_files
      322.             self._post, self._files = QueryDict(self.body, encoding=self._encoding), MultiValueDict()

    File "C:\Users\bob\Documents\Projects\potato-face\env\lib\site-packages\django\http\request.py" in body
      283.                 self._body = self.read()

    File "C:\Users\bob\Documents\Projects\potato-face\env\lib\site-packages\django\http\request.py" in read
      342.             return self._stream.read(*args, **kwargs)

    File "C:\Users\bob\Documents\Projects\potato-face\env\lib\site-packages\django\core\handlers\wsgi.py" in read
      36.             result = self.buffer + self._read_limited()

    Exception Type: TypeError at /api/admin/login/
    Exception Value: can't concat str to bytes

Any ideas what it might be?

John

**Comment by james1293** [comment]
John, can you let me know if my pull request fixes that issue for you? It fixed it for me.

**Comment by dllabs** [comment]
Thanks James, that fixed it!

What was the issue? Was there a change to Django's WSGI that broke the azure adapter? I only just installed the adapter yesterday. I can't imagine it was always broken like this...

As a side note, the Django admin console now works, but without any of its styling. What does one have to do to get static assets through the adapter?

cheers

John

**Comment by james1293** [comment]
Idk if the change was on the Django side or the Azure Functions side. I tend to think the AF side because AF  for Python is still in "Preview".

I don't know if there is a proper way to make static assets work (that is, to make Azure serve them directly), so I told Django to serve them:

1. Add the following to the bottom of `djangoProjectFolder/djangoProjectFolder/urls.py` :

		from django.conf import settings
		from django.conf.urls.static import static
		urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

2. In settings.py, make sure STATIC_URL has "/app" (or whatever prefix you are using) at the beginning. For example,

          STATIC_URL  = '/app/static/'

3. In settings.py:
  
         STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

4. From the terminal:
  
         python manage.py collectstatic

**Comment by sdementen** [comment]
I had the issue today with Azure Functions + Django 3.0.
Will this PR be merged soon ? with a new PyPI version ?
